config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :users, only: [:index, :show]

  resources :podcasts, except: [:edit] do
    resources :episodes, except: [:index, :edit]

    member do
      get :deploy
    end
  end

  root to: 'podcasts#index'
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
  has_many :episodes, dependent: :destroy, inverse_of: :podcast

  attachment :image

  validates :title,       presence: true
  validates :link,        presence: true
  validates :language,    presence: true
  validates :copyright,   presence: true
  validates :subtitle,    presence: true
  validates :author,      presence: true
  validates :description, presence: true
  validates :email,       presence: true
  validates :image,       presence: true
  validates :categories,  presence: true

  after_commit :deploy

  def is_video?
    episodes.with_video.any?
  end

  def deploy
    DeployPodcastJob.perform_later self
  end
end

# == Schema Information
#
# Table name: podcasts
#
#  id          :integer          not null, primary key
#  title       :string
#  link        :string
#  language    :string           default("en-us")
#  copyright   :string
#  subtitle    :string
#  author      :string
#  description :string
#  email       :string
#  image_id    :string
#  categories  :string           is an Array
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  respond_to :html, :rss
  skip_before_action :authenticate_user!, only: [:show]

  resource :podcast do
    modify :title, :link, :language, :copyright, :subtitle, :author, :description, :email, :image, :categories
  end

  def index
    respond_with podcasts
  end

  def new
    render :new
  end

  def show
    respond_with podcast
  end

  def create
    podcast.save
    respond_with podcast
  end

  def update
    podcast.update_attributes(edit_params)
    respond_with podcast
  end

  def destroy
    podcast.destroy
    respond_with podcasts_path, change: 'podcasts'
  end

  def deploy
    if DeployPodcastJob.perform_later(podcast)
      redirect_to podcast, notice: I18n.t('flash.actions.deploy.notice')
    else
      redirect_to podcast, alert: I18n.t('flash.actions.deploy.alert')
    end
  end
end

app/views/podcasts/_form.html.haml
= simple_form_for podcast, remote: true do |f|
  = f.input :title
  = f.input :link
  = f.input :language
  = f.input :copyright
  = f.input :subtitle
  = f.input :author
  = f.input :description
  = f.input :email, as: :email
  = f.input :image, as: :attachment
  = f.input :categories

  .controls
    = f.submit 'Save'

app/views/podcasts/index.html.haml
= title 'Podcasts'

.podcasts
  - if podcasts.any?
    - cache cache_key_for_podcasts do
      %p
        = link_to_modal 'Manage New Podcast', new_podcast_path, class: 'button'
      %dl
        - podcasts.map(&:decorate).each do |podcast|
          - cache podcast do
            %dt= link_to podcast.title, podcast
            %dd
              = image_tag podcast.image_url
              %p= podcast.description
              %p= link_to 'Delete', podcast, remote: true, class: 'delete button'
  - else
    .empty
      %h2
        There are no podcasts.
        = link_to_modal 'Add one?', new_podcast_path

app/views/podcasts/new.html.haml
= title 'New Podcast'
= render 'form'

app/views/podcasts/show.html.haml
= title podcast.title

#podcast
  .title
    %h2 Edit
    = link_to 'Deploy', deploy_podcast_path(podcast), class: 'large deploy button success', remote: true

  .details
    = render 'form'

  #episodes
    %h2 Episodes

    - cache cache_key_for_episodes(podcast) do
      %table
        %thead
          %tr
            %th.title Title
            %th.duration Duration
            %th.controls
              = link_to_modal 'Upload', new_podcast_episode_path(podcast), class: 'upload button secondary'

        %tbody
          - podcast.episodes.in_sequence.map(&:decorate).each do |episode|
            - cache episode do
              %tr{ id: "episodes:#{episode.id}", itemid: episode.id }
                %td.image= image_tag episode.image_url
                %td.title= link_to episode.title, episode
                %td.duration= episode.duration
                %td.controls
                  %nav
                    = link_to 'Download', episode.download_url, class: 'download button'
                    = link_to_modal 'Edit', episode, class: 'edit button'
                    = link_to 'Delete', episode, class: 'delete button', method: :delete

app/views/podcasts/show.rss.erb
<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd" version="2.0">
  <channel>
    <title><%= podcast.title %></title>
    <link><%= podcast.link %></link>
    <language><%= podcast.language %></language>
    <copyright><%= podcast.copyright %></copyright>

    <itunes:subtitle><%= podcast.subtitle %></itunes:subtitle>
    <itunes:author><%= podcast.author %></itunes:author>
    <itunes:summary><%= podcast.description %></itunes:summary>

    <description><%= podcast.description %></description>

    <itunes:owner>
      <itunes:name><%= podcast.author %></itunes:name>
      <itunes:email><%= podcast.email %></itunes:email>
    </itunes:owner>

    <itunes:image href="<%= podcast.image_url %>" />

    <% podcast.categories.each do |category| %>
      <itunes:category text="<%= category %>" />
    <% end %>

    <% podcast.episodes.in_sequence.map(&:decorate).each do |episode| %>
        <title><%= episode.title %></title>
        <itunes:author><%= episode.author %></itunes:author>
        <itunes:subtitle><%= episode.subtitle %></itunes:subtitle>
        <itunes:summary><![CDATA[<%= episode.summary %>]]></itunes:summary>
        <itunes:image href="<%= episode.image_url %>" />
        <enclosure url="<%= episode.download_url %>" length="<%= episode.enclosure.size %>" type="<%= episode.enclosure.content_type %>" />
        <guid><%= episode.download_url %></guid>
        <pubDate><%= episode.published_at %></pubDate>
        <itunes:duration><%= episode.duration %></itunes:duration>
      </item>
    <% end %>
 </channel>
</rss>